// Export utilities for generating PDFs and shareable content

import { Circuit } from './types';
import { CITIES } from './data';

export class ExportUtils {
  /**
   * Generate Faculty PDF content
   */
  static generateFacultyPDF(circuit: Circuit): string {
    const cities = circuit.cities.map(id => CITIES.find(c => c.id === id)).filter(Boolean);
    
    let content = `ARCHITECTURE STUDY TOUR CIRCUIT
Faculty Planning Document

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CIRCUIT OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Circuit Name: ${circuit.name}
Academic Year: Year ${circuit.academic_year}
${circuit.semester ? `Semester: ${circuit.semester}` : ''}
Duration: ${circuit.duration} days
Status: ${circuit.status}

Cities Covered: ${circuit.cities.map(id => {
  const city = CITIES.find(c => c.id === id);
  return city ? city.city : id;
}).join(' → ')}


LEARNING OUTCOMES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Primary Learning Goals:
${circuit.learning_goals.map(goal => `• ${goal}`).join('\n')}


ACADEMIC JUSTIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${circuit.academic_justification}


CIRCUIT SCORING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Overall Academic Score: ${circuit.score.total}/100

Breakdown:
• Academic Match: ${circuit.score.academic_match}/100
• Travel Efficiency: ${circuit.score.travel_efficiency}/100
• Pedagogical Progression: ${circuit.score.pedagogical_progression}/100
• User Preference Match: ${circuit.score.user_preference}/100


DAY-WISE ACADEMIC PLAN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${circuit.day_plan.map(day => `
Day ${day.day} - ${day.city}
${'-'.repeat(50)}

Learning Focus: ${day.learning_focus.join(', ')}

Morning (9:00 AM - 12:30 PM)
${day.morning}

Afternoon (2:00 PM - 5:30 PM)
${day.afternoon}

Evening (6:00 PM - 8:00 PM)
${day.evening}

`).join('\n')}


EVALUATION MAPPING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Suggested Evaluation Criteria:

1. Daily Sketches and Measured Drawings (30%)
   - Quality of observation
   - Accuracy of documentation
   - Analytical depth

2. Reflective Journal (20%)
   - Daily reflections
   - Synthesis of learnings
   - Critical thinking

3. Final Presentation (30%)
   - Comprehensive documentation
   - Clarity of analysis
   - Visual communication

4. Group Discussion Participation (20%)
   - Active engagement
   - Peer learning contribution
   - Question quality


LOGISTICAL NOTES FOR FACULTY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${cities.map((city, index) => city ? `
${city.city}, ${city.state}
• Suggested Duration: ${city.suggested_days} days
• Travel Nodes: ${city.travel_nodes.join(', ')}
${city.risk_notes ? `• Note: ${city.risk_notes}` : ''}
${index < cities.length - 1 ? `• Next Destination: ${cities[index + 1]?.city || 'N/A'}` : ''}
` : '').join('\n')}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by ArchCircuit - Architecture Study Tour Circuit Builder
${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

    return content;
  }

  /**
   * Generate Student Brief PDF content
   */
  static generateStudentBrief(circuit: Circuit): string {
    let content = `ARCHITECTURE STUDY TOUR
Student Brief

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TOUR OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Circuit: ${circuit.name}
Duration: ${circuit.duration} days
Academic Year: Year ${circuit.academic_year}


WHAT TO EXPECT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This study tour is designed to deepen your understanding of:
${circuit.learning_goals.map(goal => `• ${goal}`).join('\n')}


WHAT TO BRING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Essential Documentation Tools:
• A4 sketchbook (minimum 50 sheets)
• Sketching pencils (HB, 2B, 4B)
• Measuring tape (5m)
• Camera / smartphone with sufficient storage
• Daily journal / notebook
• Drawing board and clips (for measured drawings)


DAILY EXPECTATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${circuit.day_plan.map(day => `
Day ${day.day} - ${day.city}
${'-'.repeat(50)}

What to Observe:
• ${day.learning_focus.join('\n• ')}

What to Document:
• Detailed sketches of key architectural elements
• Measured drawings (as assigned by faculty)
• Photographs with annotations
• Personal observations and reflections

Morning Activity:
${day.morning}

Afternoon Activity:
${day.afternoon}

Evening Session:
${day.evening}

`).join('\n')}


DOCUMENTATION GUIDELINES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Sketching:
• Focus on understanding, not perfection
• Annotate your sketches with dimensions and observations
• Draw what you see, not what you think you know
• Capture details: materials, joinery, construction techniques

Photography:
• Supplement, don't replace sketching
• Photograph overall views and specific details
• Consider lighting and composition
• Take reference photos for later sketching

Journaling:
• Write daily reflections
• Note questions that arise during visits
• Record conversations with faculty and peers
• Connect observations to coursework


EVALUATION CRITERIA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Your work will be evaluated on:

1. Quality of Documentation (30%)
   - Completeness and depth of sketches
   - Accuracy of measured drawings
   - Quality of observations

2. Reflective Thinking (20%)
   - Daily journal entries
   - Synthesis of learning
   - Critical analysis

3. Final Submission (30%)
   - Comprehensive documentation portfolio
   - Clear presentation of learnings
   - Visual communication quality

4. Participation (20%)
   - Engagement during site visits
   - Contribution to group discussions
   - Peer learning


PROFESSIONAL CONDUCT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

• Be punctual for all scheduled activities
• Dress appropriately for site visits
• Respect the sites and buildings you visit
• Seek permission before photographing private spaces
• Engage respectfully with local communities
• Follow all safety guidelines during site visits


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is an academic learning journey. Make the most of it.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

    return content;
  }

  /**
   * Generate PPT Outline content
   */
  static generatePPTOutline(circuit: Circuit): string {
    const cities = circuit.cities.map(id => CITIES.find(c => c.id === id)).filter(Boolean);

    let content = `ARCHITECTURE STUDY TOUR PRESENTATION
PowerPoint Outline

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SLIDE 1: Title Slide
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: ${circuit.name}
• Subtitle: Year ${circuit.academic_year} Architecture Study Tour
• Duration: ${circuit.duration} days
• [Include circuit route map]


SLIDE 2: Learning Objectives
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Learning Goals
• Content:
${circuit.learning_goals.map(goal => `  - ${goal}`).join('\n')}


SLIDE 3: Academic Justification
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Why This Circuit?
• Content: ${circuit.academic_justification}


SLIDE 4: Circuit Overview
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Circuit Route
• Visual: Map showing city sequence
• Cities: ${cities.map(c => c?.city).join(' → ')}


${cities.map((city, index) => city ? `
SLIDE ${5 + index * 3}: ${city.city} - Introduction
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: ${city.city}, ${city.state}
• Context image
• Key Facts:
  - Region: ${city.region}
  - Duration: ${city.suggested_days} days
  - Focus: ${city.learning_focus.slice(0, 2).join(', ')}


SLIDE ${6 + index * 3}: ${city.city} - Key Learnings
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Learning Focus: ${city.city}
• Content:
${city.learning_focus.map(f => `  - ${f}`).join('\n')}


SLIDE ${7 + index * 3}: ${city.city} - Activities
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Site Activities in ${city.city}
• Content:
${circuit.day_plan
  .filter(day => day.city === city.city)
  .map(day => `  Day ${day.day}:
  - Morning: ${day.morning}
  - Afternoon: ${day.afternoon}`)
  .join('\n')}
` : '').join('\n')}


SLIDE ${5 + cities.length * 3}: Evaluation Framework
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Assessment Criteria
• Content:
  - Daily Documentation: 30%
  - Reflective Journal: 20%
  - Final Presentation: 30%
  - Participation: 20%


SLIDE ${6 + cities.length * 3}: Expected Outcomes
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: What Students Will Gain
• Content:
  - Practical understanding of architectural principles
  - Direct observation of building systems
  - Exposure to diverse architectural typologies
  - Enhanced documentation skills
  - Critical thinking and analytical abilities


SLIDE ${7 + cities.length * 3}: Questions
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Title: Questions?
• Contact information


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Slides: ${7 + cities.length * 3}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

    return content;
  }

  /**
   * Download text content as file
   */
  static downloadTextFile(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Generate shareable link (base64 encoded circuit ID)
   */
  static generateShareableLink(circuitId: string): string {
    const baseUrl = window.location.origin;
    const encoded = btoa(circuitId);
    return `${baseUrl}?circuit=${encoded}`;
  }

  /**
   * Parse shareable link
   */
  static parseShareableLink(url: string): string | null {
    try {
      const urlObj = new URL(url);
      const encoded = urlObj.searchParams.get('circuit');
      return encoded ? atob(encoded) : null;
    } catch {
      return null;
    }
  }
}
